# Butterfly theme configuration.
# Full docs: https://butterfly.js.org/

menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  语言: "javascript:window.translateFn&&window.translateFn.translatePage() || fas fa-language"

nav:
  logo:
  display_title: true
  fixed: false

avatar:
  img:
  effect: false

favicon: /img/favicon.png

index_img: /img/home-banner.png
default_top_img:
archive_img:
tag_img:
category_img:

subtitle:
  enable: true
  effect: false
  typed_option:
  source: false
  sub:
    - 梨花落雪染衣襟，
    - 一笔春光入画深。
    - 眉间藏了三分月，
    - 眼底流着万里云。
    - 衣袂轻扬风自懂，
    - 梨香暗渡夜无声。
    - 绘你不需丹青手，
    - 只消一眼，便是诗。

cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both
  default_cover:

error_404:
  enable: true
  subtitle: 页面没有找到
  background: /img/error-page.png

post_meta:
  page:
    date_type: created
    date_format: date
    categories: true
    tags: false
    label: true
  post:
    date_type: both
    date_format: date
    categories: true
    tags: true
    label: true

aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  card_author:
    enable: true
    description: 技术、学习与生活记录
    button:
      enable: false
  card_announcement:
    enable: true
    content: 欢迎来到我的个人博客。
  card_recent_post:
    enable: true
    limit: 5
    sort: date
    sort_order:
  card_categories:
    enable: true
    limit: 8
    expand: none
    sort_order:
  card_tags:
    enable: true
    limit: 20
    color: false
    sort_order:
  card_archives:
    enable: true
    type: monthly
    format: MMMM YYYY
    order: -1
    limit: 8
    sort_order:
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true

social:
  fab fa-github: https://github.com/Kai-Su2002 || GitHub

footer:
  owner:
    enable: true
    since: 2026
  custom_text:
  copyright: true

translate:
  enable: true
  default: 繁
  defaultEncoding: 2
  translateDelay: 0
  msgToTraditionalChinese: 繁
  msgToSimplifiedChinese: 簡

search:
  use: local_search
  placeholder: 搜索文章
  local_search:
    preload: false
    top_n_per_article: 1
    unescape: false
    pagination:
      enable: false
      hitsPerPage: 8
    CDN:

comments:
  use:

inject:
  head:
  bottom:
