# Butterfly theme configuration.
# Full docs: https://butterfly.js.org/

menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  关于: /about/ || fas fa-user

nav:
  logo:
  display_title: true
  fixed: false

avatar:
  img:
  effect: false

favicon: /img/favicon.png

index_img:
default_top_img:
archive_img:
tag_img:
category_img:

cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both
  default_cover:

post_meta:
  page:
    date_type: created
    date_format: date
    categories: true
    tags: false
    label: true
  post:
    date_type: both
    date_format: date
    categories: true
    tags: true
    label: true

aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  card_author:
    enable: true
    description: 技术、学习与生活记录
    button:
      enable: false
  card_announcement:
    enable: true
    content: 欢迎来到我的个人博客。
  card_recent_post:
    enable: true
    limit: 5
    sort: date
    sort_order:
  card_categories:
    enable: true
    limit: 8
    expand: none
    sort_order:
  card_tags:
    enable: true
    limit: 20
    color: false
    sort_order:
  card_archives:
    enable: true
    type: monthly
    format: MMMM YYYY
    order: -1
    limit: 8
    sort_order:
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true

social:
  fab fa-github: https://github.com/Kai-Su2002 || GitHub

footer:
  owner:
    enable: true
    since: 2026
  custom_text:
  copyright: true

local_search:
  enable: false

comments:
  use:

inject:
  head:
  bottom:
